name: TEST

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: MYXOMOPX/modify-pkg-json@master
        with: 
          target: ./package.json
          action: "update_version"
          argument: "1.6.6"
          
      - name: Read package.json
        id: rpkg
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json
          
      - name: Echo package.json
        run: echo ${{ steps.rpkg.outputs.content }}
