name: TEST

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      
      - uses: pCYSl5EDgo/cat@master
        id: logA
        with:
          path: ./package.json

      - run: echo $TEXT
        env:
          TEXT: ${{ steps.logA.outputs.text }}
    
      - uses: MYXOMOPX/modify-pkg-json@master
        with: 
          target: ./package.json
          action: "set_version"
          argument: "1.6.6"
          
      - uses: MYXOMOPX/modify-pkg-json@master
        with: 
          target: ./package.json
          action: "set_dep_version"
          argument: "react 1.2.3"
          
      - uses: MYXOMOPX/modify-pkg-json@master
        with: 
          target: ./package.json
          action: "set_devdep_version"
          argument: "jest 100.200.300"
          
      - uses: pCYSl5EDgo/cat@master
        id: logB
        with:
          path: ./package.json

      - run: echo $TEXT
        env:
          TEXT: ${{ steps.logB.outputs.text }}
